---
#Port number defintion
server:
  port: 8888
#Authorization flag  
security:
  basic:
    enabled: true
  user:
    name: pluralsight
    password: praveen
#remote config file setting    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/praveen2710/MicroServices
#          username: praveen2710 
#          password: ap31ae9142
          search-paths:
          - tolls-config/github-pluralsight-spring-cloudconfig-wa-tolls
          - tolls-config/github-pluralsight-spring-cloudconfig-wa-tolls/station*
#          - tolls-config/github-pluralsight-spring-cloudconfig-wa-tolls-perf          
        encrypt:
          enabled: false
